#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
# see also: https://unix.stackexchange.com/questions/257571/why-does-bashrc-check-whether-the-current-shell-is-interactive#257613

# prevent new terminals to open a new session in the same directory as another terminal is in
cd

# +++ ATTENTION +++
# start tmux with every shell start
# If not running interactively, do not do anything
#[[ $- != *i* ]] && return
#[[ -z "$TMUX" ]] && exec tmux
# +++++++++++++++++

# prevent history commands from executing by ! or !! but wait for execution by user
shopt -s histverify

# notify user if restart necessary
bold=$(tput bold)
normal=$(tput sgr0)

# after greeting include additional file with commands (won't be commited)
if [ -f $HOME/.bash_ext ]; then
	. $HOME/.bash_ext
fi

if [ -f $HOME/.bash_funcs ]; then
	. $HOME/.bash_funcs
fi

# alias's
alias diff='diff --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ls='ls -hrt --color=auto'
alias ll='ls -Al'
# force tmux to assume 256 color mode
alias tmux='tmux -2'
# this might cause some trouble
alias python='bpython'
# gcc output color
export GCC_COLORS='error=01;31:warning=01;33:note=01;35:caret=01;32:locus=01:quote=01'
# less colorized
export LESS=-RS
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
# grep color
export GREP_COLOR="1;32"

# man color hack
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# pacman and aur helper
alias paorph='yay -Rns $(yay -Qdtq) '
alias paup='yay -Syu '

# btrfs
#alias buh='sudo btrfs filesystem usage /home'
alias buh='sudo echo ""; echo "/home usage"; sudo btrfs filesystem usage /home | grep -E "^\s+(Used|Free \(estimated\)):";echo ""'
#alias bur='sudo btrfs filesystem usage /'
alias bur='sudo echo ""; echo "/ usage"; sudo btrfs filesystem usage / | grep -E "^\s+(Used|Free \(estimated\)):";echo ""'

PROMPT_COMMAND=git_prompt
#PS1='\u@\h \W >> '
 
HISTTIMEFORMAT="[%Y-%m-%d %T %Z] "
HISTCONTROL=erasedups
HISTSIZE=100000
HISTFILESIZE=100000

# add my scripts to PATH
PATH=$PATH:$HOME/projects/scripts
PATH=$PATH:$HOME/.local/bin
export EDITOR=vim
export PAGER=less

# Make flags
export MAKEFLAGS="-j$(grep -c ^processor /proc/cpuinfo)"

# greeting with logo
archey3
